/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The approval statement status. Possible values include:    - &#x60;UnSend&#x60;: The request has not send.   - &#x60;Wait&#x60;: The request sent to broker user ,waiting audit.    - &#x60;Approve&#x60;: The user approved.   - &#x60;Reject&#x60;: The user rejected.   - &#x60;Invalid&#x60;: The request invalid.   - &#x60;Timeout&#x60;: The request timeout. 
 */
@JsonAdapter(ApprovalStatementStatus.Adapter.class)
public enum ApprovalStatementStatus {
  UNKNOWN(null),
  
  UNSEND("UnSend"),
  
  WAITAUDIT("WaitAudit"),
  
  APPROVE("Approve"),
  
  REJECT("Reject"),
  
  INVALID("Invalid"),
  
  TIMEOUT("Timeout");

  private String value;

  ApprovalStatementStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ApprovalStatementStatus fromValue(String value) {
    for (ApprovalStatementStatus b : ApprovalStatementStatus.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ApprovalStatementStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final ApprovalStatementStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ApprovalStatementStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ApprovalStatementStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ApprovalStatementStatus.fromValue(value);
  }
}

