/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The mode of transaction fee payment using Fee Station. Currently, Fee Station supports EVM-compatible and TRON transactions initiated from MPC Wallets (Organization-Controlled). For more details, refer to [Fee Station](https://manuals.cobo.com/en/portal/fee-station/introduction). - &#x60;ProActiveAutoFuel&#x60;: Always use Fee Station to pay transaction fees. - &#x60;PassiveAutoFuel&#x60;: Use Fee Station only when the source address balance is insufficient to cover the transaction fees.  Please note that the TRON chain does not support &#x60;PassiveAutoFuel&#x60; due to its fee delegation mechanism. 
 */
@JsonAdapter(AutoFuelType.Adapter.class)
public enum AutoFuelType {
  UNKNOWN(null),
  
  PASSIVEAUTOFUEL("PassiveAutoFuel"),
  
  PROACTIVEAUTOFUEL("ProActiveAutoFuel");

  private String value;

  AutoFuelType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AutoFuelType fromValue(String value) {
    for (AutoFuelType b : AutoFuelType.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AutoFuelType> {
    @Override
    public void write(final JsonWriter jsonWriter, final AutoFuelType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AutoFuelType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AutoFuelType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    AutoFuelType.fromValue(value);
  }
}

