/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The status of babylon airdrop/staking registration request.
 */
@JsonAdapter(BabylonRegistrationRequestStatus.Adapter.class)
public enum BabylonRegistrationRequestStatus {
  UNKNOWN(null),
  
  PROCESSING("Processing"),
  
  COMPLETED("Completed"),
  
  FAILED("Failed");

  private String value;

  BabylonRegistrationRequestStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static BabylonRegistrationRequestStatus fromValue(String value) {
    for (BabylonRegistrationRequestStatus b : BabylonRegistrationRequestStatus.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<BabylonRegistrationRequestStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final BabylonRegistrationRequestStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public BabylonRegistrationRequestStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return BabylonRegistrationRequestStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    BabylonRegistrationRequestStatus.fromValue(value);
  }
}

