/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cobo.waas2.JSON;

/**
 * Pop information to be used for airdrop registration.
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class BabylonAirdropPop {
  public static final String SERIALIZED_NAME_BABY_ADDRESS = "baby_address";
  @SerializedName(SERIALIZED_NAME_BABY_ADDRESS)
  private String babyAddress;

  public static final String SERIALIZED_NAME_BTC_ADDRESS = "btc_address";
  @SerializedName(SERIALIZED_NAME_BTC_ADDRESS)
  private String btcAddress;

  public static final String SERIALIZED_NAME_BTC_PUBLIC_KEY = "btc_public_key";
  @SerializedName(SERIALIZED_NAME_BTC_PUBLIC_KEY)
  private String btcPublicKey;

  public static final String SERIALIZED_NAME_BTC_SIGN_BABY = "btc_sign_baby";
  @SerializedName(SERIALIZED_NAME_BTC_SIGN_BABY)
  private String btcSignBaby;

  public static final String SERIALIZED_NAME_BABY_SIGN_BTC = "baby_sign_btc";
  @SerializedName(SERIALIZED_NAME_BABY_SIGN_BTC)
  private String babySignBtc;

  public static final String SERIALIZED_NAME_BABY_PUBLIC_KEY = "baby_public_key";
  @SerializedName(SERIALIZED_NAME_BABY_PUBLIC_KEY)
  private String babyPublicKey;

  public BabylonAirdropPop() {
  }

  public BabylonAirdropPop babyAddress(String babyAddress) {
    this.babyAddress = babyAddress;
    return this;
  }

   /**
   * BABY address
   * @return babyAddress
  **/
  @javax.annotation.Nonnull
  public String getBabyAddress() {
    return babyAddress;
  }

  public void setBabyAddress(String babyAddress) {
    this.babyAddress = babyAddress;
  }


  public BabylonAirdropPop btcAddress(String btcAddress) {
    this.btcAddress = btcAddress;
    return this;
  }

   /**
   * BTC address
   * @return btcAddress
  **/
  @javax.annotation.Nonnull
  public String getBtcAddress() {
    return btcAddress;
  }

  public void setBtcAddress(String btcAddress) {
    this.btcAddress = btcAddress;
  }


  public BabylonAirdropPop btcPublicKey(String btcPublicKey) {
    this.btcPublicKey = btcPublicKey;
    return this;
  }

   /**
   * BTC public key in hex format
   * @return btcPublicKey
  **/
  @javax.annotation.Nonnull
  public String getBtcPublicKey() {
    return btcPublicKey;
  }

  public void setBtcPublicKey(String btcPublicKey) {
    this.btcPublicKey = btcPublicKey;
  }


  public BabylonAirdropPop btcSignBaby(String btcSignBaby) {
    this.btcSignBaby = btcSignBaby;
    return this;
  }

   /**
   * BTC sign BABY
   * @return btcSignBaby
  **/
  @javax.annotation.Nonnull
  public String getBtcSignBaby() {
    return btcSignBaby;
  }

  public void setBtcSignBaby(String btcSignBaby) {
    this.btcSignBaby = btcSignBaby;
  }


  public BabylonAirdropPop babySignBtc(String babySignBtc) {
    this.babySignBtc = babySignBtc;
    return this;
  }

   /**
   * BABY sign BTC
   * @return babySignBtc
  **/
  @javax.annotation.Nonnull
  public String getBabySignBtc() {
    return babySignBtc;
  }

  public void setBabySignBtc(String babySignBtc) {
    this.babySignBtc = babySignBtc;
  }


  public BabylonAirdropPop babyPublicKey(String babyPublicKey) {
    this.babyPublicKey = babyPublicKey;
    return this;
  }

   /**
   * BABY public key in base64 format
   * @return babyPublicKey
  **/
  @javax.annotation.Nonnull
  public String getBabyPublicKey() {
    return babyPublicKey;
  }

  public void setBabyPublicKey(String babyPublicKey) {
    this.babyPublicKey = babyPublicKey;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the BabylonAirdropPop instance itself
   */
  public BabylonAirdropPop putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BabylonAirdropPop babylonAirdropPop = (BabylonAirdropPop) o;
    return Objects.equals(this.babyAddress, babylonAirdropPop.babyAddress) &&
        Objects.equals(this.btcAddress, babylonAirdropPop.btcAddress) &&
        Objects.equals(this.btcPublicKey, babylonAirdropPop.btcPublicKey) &&
        Objects.equals(this.btcSignBaby, babylonAirdropPop.btcSignBaby) &&
        Objects.equals(this.babySignBtc, babylonAirdropPop.babySignBtc) &&
        Objects.equals(this.babyPublicKey, babylonAirdropPop.babyPublicKey)&&
        Objects.equals(this.additionalProperties, babylonAirdropPop.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(babyAddress, btcAddress, btcPublicKey, btcSignBaby, babySignBtc, babyPublicKey, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BabylonAirdropPop {\n");
    sb.append("    babyAddress: ").append(toIndentedString(babyAddress)).append("\n");
    sb.append("    btcAddress: ").append(toIndentedString(btcAddress)).append("\n");
    sb.append("    btcPublicKey: ").append(toIndentedString(btcPublicKey)).append("\n");
    sb.append("    btcSignBaby: ").append(toIndentedString(btcSignBaby)).append("\n");
    sb.append("    babySignBtc: ").append(toIndentedString(babySignBtc)).append("\n");
    sb.append("    babyPublicKey: ").append(toIndentedString(babyPublicKey)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("baby_address");
    openapiFields.add("btc_address");
    openapiFields.add("btc_public_key");
    openapiFields.add("btc_sign_baby");
    openapiFields.add("baby_sign_btc");
    openapiFields.add("baby_public_key");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("baby_address");
    openapiRequiredFields.add("btc_address");
    openapiRequiredFields.add("btc_public_key");
    openapiRequiredFields.add("btc_sign_baby");
    openapiRequiredFields.add("baby_sign_btc");
    openapiRequiredFields.add("baby_public_key");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to BabylonAirdropPop
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BabylonAirdropPop.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BabylonAirdropPop is not found in the empty JSON string", BabylonAirdropPop.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BabylonAirdropPop.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("baby_address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `baby_address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("baby_address").toString()));
      }
      if (!jsonObj.get("btc_address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `btc_address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("btc_address").toString()));
      }
      if (!jsonObj.get("btc_public_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `btc_public_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("btc_public_key").toString()));
      }
      if (!jsonObj.get("btc_sign_baby").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `btc_sign_baby` to be a primitive type in the JSON string but got `%s`", jsonObj.get("btc_sign_baby").toString()));
      }
      if (!jsonObj.get("baby_sign_btc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `baby_sign_btc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("baby_sign_btc").toString()));
      }
      if (!jsonObj.get("baby_public_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `baby_public_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("baby_public_key").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BabylonAirdropPop.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BabylonAirdropPop' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BabylonAirdropPop> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BabylonAirdropPop.class));

       return (TypeAdapter<T>) new TypeAdapter<BabylonAirdropPop>() {
           @Override
           public void write(JsonWriter out, BabylonAirdropPop value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() == null)
                   obj.addProperty(entry.getKey(), (String) null);
                 else if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public BabylonAirdropPop read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             BabylonAirdropPop instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BabylonAirdropPop given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BabylonAirdropPop
  * @throws IOException if the JSON string is invalid with respect to BabylonAirdropPop
  */
  public static BabylonAirdropPop fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BabylonAirdropPop.class);
  }

 /**
  * Convert an instance of BabylonAirdropPop to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

