/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.cobo.waas2.model.EthStakingExtraAllOfBeaconValidators;
import com.cobo.waas2.model.StakingPoolType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cobo.waas2.JSON;

/**
 * EthStakingExtra
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class EthStakingExtra {
  public static final String SERIALIZED_NAME_POOL_TYPE = "pool_type";
  @SerializedName(SERIALIZED_NAME_POOL_TYPE)
  private StakingPoolType poolType;

  public static final String SERIALIZED_NAME_POS_CHAIN = "pos_chain";
  @SerializedName(SERIALIZED_NAME_POS_CHAIN)
  private String posChain;

  public static final String SERIALIZED_NAME_BEACON_VALIDATORS = "beacon_validators";
  @SerializedName(SERIALIZED_NAME_BEACON_VALIDATORS)
  private List<EthStakingExtraAllOfBeaconValidators> beaconValidators = new ArrayList<>();

  public EthStakingExtra() {
  }

  public EthStakingExtra poolType(StakingPoolType poolType) {
    this.poolType = poolType;
    return this;
  }

   /**
   * Get poolType
   * @return poolType
  **/
  @javax.annotation.Nonnull
  public StakingPoolType getPoolType() {
    return poolType;
  }

  public void setPoolType(StakingPoolType poolType) {
    this.poolType = poolType;
  }


  public EthStakingExtra posChain(String posChain) {
    this.posChain = posChain;
    return this;
  }

   /**
   * The Proof-of-Stake (PoS) chain.
   * @return posChain
  **/
  @javax.annotation.Nonnull
  public String getPosChain() {
    return posChain;
  }

  public void setPosChain(String posChain) {
    this.posChain = posChain;
  }


  public EthStakingExtra beaconValidators(List<EthStakingExtraAllOfBeaconValidators> beaconValidators) {
    this.beaconValidators = beaconValidators;
    return this;
  }

  public EthStakingExtra addBeaconValidatorsItem(EthStakingExtraAllOfBeaconValidators beaconValidatorsItem) {
    if (this.beaconValidators == null) {
      this.beaconValidators = new ArrayList<>();
    }
    this.beaconValidators.add(beaconValidatorsItem);
    return this;
  }

   /**
   * The list of validator information.
   * @return beaconValidators
  **/
  @javax.annotation.Nullable
  public List<EthStakingExtraAllOfBeaconValidators> getBeaconValidators() {
    return beaconValidators;
  }

  public void setBeaconValidators(List<EthStakingExtraAllOfBeaconValidators> beaconValidators) {
    this.beaconValidators = beaconValidators;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the EthStakingExtra instance itself
   */
  public EthStakingExtra putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EthStakingExtra ethStakingExtra = (EthStakingExtra) o;
    return Objects.equals(this.poolType, ethStakingExtra.poolType) &&
        Objects.equals(this.posChain, ethStakingExtra.posChain) &&
        Objects.equals(this.beaconValidators, ethStakingExtra.beaconValidators)&&
        Objects.equals(this.additionalProperties, ethStakingExtra.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(poolType, posChain, beaconValidators, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EthStakingExtra {\n");
    sb.append("    poolType: ").append(toIndentedString(poolType)).append("\n");
    sb.append("    posChain: ").append(toIndentedString(posChain)).append("\n");
    sb.append("    beaconValidators: ").append(toIndentedString(beaconValidators)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pool_type");
    openapiFields.add("pos_chain");
    openapiFields.add("beacon_validators");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("pool_type");
    openapiRequiredFields.add("pos_chain");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to EthStakingExtra
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EthStakingExtra.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EthStakingExtra is not found in the empty JSON string", EthStakingExtra.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EthStakingExtra.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `pool_type`
      StakingPoolType.validateJsonElement(jsonObj.get("pool_type"));
      if (!jsonObj.get("pos_chain").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pos_chain` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pos_chain").toString()));
      }
      if (jsonObj.get("beacon_validators") != null && !jsonObj.get("beacon_validators").isJsonNull()) {
        JsonArray jsonArraybeaconValidators = jsonObj.getAsJsonArray("beacon_validators");
        if (jsonArraybeaconValidators != null) {
          // ensure the json data is an array
          if (!jsonObj.get("beacon_validators").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `beacon_validators` to be an array in the JSON string but got `%s`", jsonObj.get("beacon_validators").toString()));
          }

          // validate the optional field `beacon_validators` (array)
          for (int i = 0; i < jsonArraybeaconValidators.size(); i++) {
            EthStakingExtraAllOfBeaconValidators.validateJsonElement(jsonArraybeaconValidators.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EthStakingExtra.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EthStakingExtra' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EthStakingExtra> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EthStakingExtra.class));

       return (TypeAdapter<T>) new TypeAdapter<EthStakingExtra>() {
           @Override
           public void write(JsonWriter out, EthStakingExtra value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() == null)
                   obj.addProperty(entry.getKey(), (String) null);
                 else if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public EthStakingExtra read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             EthStakingExtra instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EthStakingExtra given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EthStakingExtra
  * @throws IOException if the JSON string is invalid with respect to EthStakingExtra
  */
  public static EthStakingExtra fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EthStakingExtra.class);
  }

 /**
  * Convert an instance of EthStakingExtra to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

