/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Specifies the type of entity. This must be &#x60;LEGAL&#x60;.
 */
@JsonAdapter(SelectedEntityType.Adapter.class)
public enum SelectedEntityType {
  UNKNOWN(null),
  
  LEGAL("LEGAL"),
  
  NATURAL("NATURAL");

  private String value;

  SelectedEntityType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SelectedEntityType fromValue(String value) {
    for (SelectedEntityType b : SelectedEntityType.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<SelectedEntityType> {
    @Override
    public void write(final JsonWriter jsonWriter, final SelectedEntityType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SelectedEntityType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SelectedEntityType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    SelectedEntityType.fromValue(value);
  }
}

