/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.cobo.waas2.model.TravelRuleDepositLegalEntity;
import com.cobo.waas2.model.TravelRuleDepositNaturalEntity;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import com.cobo.waas2.JSON;

@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class TravelRuleDepositExchangesOrVASPEntityInfo extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(TravelRuleDepositExchangesOrVASPEntityInfo.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!TravelRuleDepositExchangesOrVASPEntityInfo.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'TravelRuleDepositExchangesOrVASPEntityInfo' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<TravelRuleDepositLegalEntity> adapterTravelRuleDepositLegalEntity = gson.getDelegateAdapter(this, TypeToken.get(TravelRuleDepositLegalEntity.class));
            final TypeAdapter<TravelRuleDepositNaturalEntity> adapterTravelRuleDepositNaturalEntity = gson.getDelegateAdapter(this, TypeToken.get(TravelRuleDepositNaturalEntity.class));

            return (TypeAdapter<T>) new TypeAdapter<TravelRuleDepositExchangesOrVASPEntityInfo>() {
                @Override
                public void write(JsonWriter out, TravelRuleDepositExchangesOrVASPEntityInfo value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `TravelRuleDepositLegalEntity`
                    if (value.getActualInstance() instanceof TravelRuleDepositLegalEntity) {
                        JsonElement element = adapterTravelRuleDepositLegalEntity.toJsonTree((TravelRuleDepositLegalEntity)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `TravelRuleDepositNaturalEntity`
                    if (value.getActualInstance() instanceof TravelRuleDepositNaturalEntity) {
                        JsonElement element = adapterTravelRuleDepositNaturalEntity.toJsonTree((TravelRuleDepositNaturalEntity)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: TravelRuleDepositLegalEntity, TravelRuleDepositNaturalEntity");
                }

                @Override
                public TravelRuleDepositExchangesOrVASPEntityInfo read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    JsonObject jsonObject = jsonElement.getAsJsonObject();

                    // use discriminator value for faster oneOf lookup
                    TravelRuleDepositExchangesOrVASPEntityInfo newTravelRuleDepositExchangesOrVASPEntityInfo = new TravelRuleDepositExchangesOrVASPEntityInfo();
                    if (jsonObject.get("selected_entity_type") == null) {
                        log.log(Level.WARNING, "Failed to lookup discriminator value for TravelRuleDepositExchangesOrVASPEntityInfo as `selected_entity_type` was not found in the payload or the payload is empty.");
                    } else  {
                        // look up the discriminator value in the field `selected_entity_type`
                        switch (jsonObject.get("selected_entity_type").getAsString()) {
                            case "LEGAL":
                                deserialized = adapterTravelRuleDepositLegalEntity.fromJsonTree(jsonObject);
                                newTravelRuleDepositExchangesOrVASPEntityInfo.setActualInstance(deserialized);
                                return newTravelRuleDepositExchangesOrVASPEntityInfo;
                            case "NATURAL":
                                deserialized = adapterTravelRuleDepositNaturalEntity.fromJsonTree(jsonObject);
                                newTravelRuleDepositExchangesOrVASPEntityInfo.setActualInstance(deserialized);
                                return newTravelRuleDepositExchangesOrVASPEntityInfo;
                            case "TravelRuleDepositLegalEntity":
                                deserialized = adapterTravelRuleDepositLegalEntity.fromJsonTree(jsonObject);
                                newTravelRuleDepositExchangesOrVASPEntityInfo.setActualInstance(deserialized);
                                return newTravelRuleDepositExchangesOrVASPEntityInfo;
                            case "TravelRuleDepositNaturalEntity":
                                deserialized = adapterTravelRuleDepositNaturalEntity.fromJsonTree(jsonObject);
                                newTravelRuleDepositExchangesOrVASPEntityInfo.setActualInstance(deserialized);
                                return newTravelRuleDepositExchangesOrVASPEntityInfo;
                            default:
                                log.log(Level.WARNING, String.format("Failed to lookup discriminator value `%s` for TravelRuleDepositExchangesOrVASPEntityInfo. Possible values: LEGAL NATURAL TravelRuleDepositLegalEntity TravelRuleDepositNaturalEntity", jsonObject.get("selected_entity_type").getAsString()));
                        }
                    }

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize TravelRuleDepositLegalEntity
                    try {
                        // validate the JSON object to see if any exception is thrown
                        TravelRuleDepositLegalEntity.validateJsonElement(jsonElement);
                        actualAdapter = adapterTravelRuleDepositLegalEntity;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'TravelRuleDepositLegalEntity'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for TravelRuleDepositLegalEntity failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'TravelRuleDepositLegalEntity'", e);
                    }
                    // deserialize TravelRuleDepositNaturalEntity
                    try {
                        // validate the JSON object to see if any exception is thrown
                        TravelRuleDepositNaturalEntity.validateJsonElement(jsonElement);
                        actualAdapter = adapterTravelRuleDepositNaturalEntity;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'TravelRuleDepositNaturalEntity'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for TravelRuleDepositNaturalEntity failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'TravelRuleDepositNaturalEntity'", e);
                    }

                    if (match == 1) {
                        TravelRuleDepositExchangesOrVASPEntityInfo ret = new TravelRuleDepositExchangesOrVASPEntityInfo();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for TravelRuleDepositExchangesOrVASPEntityInfo: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public TravelRuleDepositExchangesOrVASPEntityInfo() {
        super("oneOf", Boolean.FALSE);
    }

    public TravelRuleDepositExchangesOrVASPEntityInfo(TravelRuleDepositLegalEntity o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public TravelRuleDepositExchangesOrVASPEntityInfo(TravelRuleDepositNaturalEntity o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("TravelRuleDepositLegalEntity", TravelRuleDepositLegalEntity.class);
        schemas.put("TravelRuleDepositNaturalEntity", TravelRuleDepositNaturalEntity.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return TravelRuleDepositExchangesOrVASPEntityInfo.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * TravelRuleDepositLegalEntity, TravelRuleDepositNaturalEntity
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof TravelRuleDepositLegalEntity) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof TravelRuleDepositNaturalEntity) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be TravelRuleDepositLegalEntity, TravelRuleDepositNaturalEntity");
    }

    /**
     * Get the actual instance, which can be the following:
     * TravelRuleDepositLegalEntity, TravelRuleDepositNaturalEntity
     *
     * @return The actual instance (TravelRuleDepositLegalEntity, TravelRuleDepositNaturalEntity)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `TravelRuleDepositLegalEntity`. If the actual instance is not `TravelRuleDepositLegalEntity`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TravelRuleDepositLegalEntity`
     * @throws ClassCastException if the instance is not `TravelRuleDepositLegalEntity`
     */
    public TravelRuleDepositLegalEntity getTravelRuleDepositLegalEntity() throws ClassCastException {
        return (TravelRuleDepositLegalEntity)super.getActualInstance();
    }
    /**
     * Get the actual instance of `TravelRuleDepositNaturalEntity`. If the actual instance is not `TravelRuleDepositNaturalEntity`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TravelRuleDepositNaturalEntity`
     * @throws ClassCastException if the instance is not `TravelRuleDepositNaturalEntity`
     */
    public TravelRuleDepositNaturalEntity getTravelRuleDepositNaturalEntity() throws ClassCastException {
        return (TravelRuleDepositNaturalEntity)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to TravelRuleDepositExchangesOrVASPEntityInfo
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with TravelRuleDepositLegalEntity
        try {
            TravelRuleDepositLegalEntity.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for TravelRuleDepositLegalEntity failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with TravelRuleDepositNaturalEntity
        try {
            TravelRuleDepositNaturalEntity.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for TravelRuleDepositNaturalEntity failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            // throw new IOException(String.format("The JSON string is invalid for TravelRuleDepositExchangesOrVASPEntityInfo with oneOf schemas: TravelRuleDepositLegalEntity, TravelRuleDepositNaturalEntity. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of TravelRuleDepositExchangesOrVASPEntityInfo given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of TravelRuleDepositExchangesOrVASPEntityInfo
     * @throws IOException if the JSON string is invalid with respect to TravelRuleDepositExchangesOrVASPEntityInfo
     */
    public static TravelRuleDepositExchangesOrVASPEntityInfo fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, TravelRuleDepositExchangesOrVASPEntityInfo.class);
    }

    /**
     * Convert an instance of TravelRuleDepositExchangesOrVASPEntityInfo to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

