/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiLogDetails
 */
public class ApiLogDetailsTest {
    private final ApiLogDetails model = new ApiLogDetails();

    /**
     * Model tests for ApiLogDetails
     */
    @Test
    public void testApiLogDetails() {
        // TODO: test ApiLogDetails
    }

    /**
     * Test the property 'logId'
     */
    @Test
    public void logIdTest() {
        // TODO: test logId
    }

    /**
     * Test the property 'apiMethod'
     */
    @Test
    public void apiMethodTest() {
        // TODO: test apiMethod
    }

    /**
     * Test the property 'apiEndpoint'
     */
    @Test
    public void apiEndpointTest() {
        // TODO: test apiEndpoint
    }

    /**
     * Test the property 'statusCode'
     */
    @Test
    public void statusCodeTest() {
        // TODO: test statusCode
    }

    /**
     * Test the property 'ipAddress'
     */
    @Test
    public void ipAddressTest() {
        // TODO: test ipAddress
    }

    /**
     * Test the property 'requestTimestamp'
     */
    @Test
    public void requestTimestampTest() {
        // TODO: test requestTimestamp
    }

    /**
     * Test the property 'apiKey'
     */
    @Test
    public void apiKeyTest() {
        // TODO: test apiKey
    }

    /**
     * Test the property 'responseBody'
     */
    @Test
    public void responseBodyTest() {
        // TODO: test responseBody
    }

    /**
     * Test the property 'queryParams'
     */
    @Test
    public void queryParamsTest() {
        // TODO: test queryParams
    }

    /**
     * Test the property 'requestBody'
     */
    @Test
    public void requestBodyTest() {
        // TODO: test requestBody
    }

}
