/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.BabylonRegistrationRequestStatus;
import com.cobo.waas2.model.StakingSource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BabylonAirdropRegistration
 */
public class BabylonAirdropRegistrationTest {
    private final BabylonAirdropRegistration model = new BabylonAirdropRegistration();

    /**
     * Model tests for BabylonAirdropRegistration
     */
    @Test
    public void testBabylonAirdropRegistration() {
        // TODO: test BabylonAirdropRegistration
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'btcAddress'
     */
    @Test
    public void btcAddressTest() {
        // TODO: test btcAddress
    }

    /**
     * Test the property 'babylonAddress'
     */
    @Test
    public void babylonAddressTest() {
        // TODO: test babylonAddress
    }

    /**
     * Test the property 'airdropAmount'
     */
    @Test
    public void airdropAmountTest() {
        // TODO: test airdropAmount
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    public void errorMessageTest() {
        // TODO: test errorMessage
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'updatedTimestamp'
     */
    @Test
    public void updatedTimestampTest() {
        // TODO: test updatedTimestamp
    }

}
