/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.RoleScopes;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetApiKeyInfo200Response
 */
public class GetApiKeyInfo200ResponseTest {
    private final GetApiKeyInfo200Response model = new GetApiKeyInfo200Response();

    /**
     * Model tests for GetApiKeyInfo200Response
     */
    @Test
    public void testGetApiKeyInfo200Response() {
        // TODO: test GetApiKeyInfo200Response
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'curveType'
     */
    @Test
    public void curveTypeTest() {
        // TODO: test curveType
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'callbackUrl'
     */
    @Test
    public void callbackUrlTest() {
        // TODO: test callbackUrl
    }

    /**
     * Test the property 'validIps'
     */
    @Test
    public void validIpsTest() {
        // TODO: test validIps
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'updatedTimestamp'
     */
    @Test
    public void updatedTimestampTest() {
        // TODO: test updatedTimestamp
    }

    /**
     * Test the property 'expiredTimestamp'
     */
    @Test
    public void expiredTimestampTest() {
        // TODO: test expiredTimestamp
    }

    /**
     * Test the property 'roleScopes'
     */
    @Test
    public void roleScopesTest() {
        // TODO: test roleScopes
    }

}
