/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.BabylonStakingExtra;
import com.cobo.waas2.model.CoreStakingExtra;
import com.cobo.waas2.model.EthStakingExtra;
import com.cobo.waas2.model.EthStakingExtraAllOfBeaconValidators;
import com.cobo.waas2.model.StakingPoolType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StakingsExtra
 */
public class StakingsExtraTest {
    private final StakingsExtra model = new StakingsExtra();

    /**
     * Model tests for StakingsExtra
     */
    @Test
    public void testStakingsExtra() {
        // TODO: test StakingsExtra
    }

    /**
     * Test the property 'poolType'
     */
    @Test
    public void poolTypeTest() {
        // TODO: test poolType
    }

    /**
     * Test the property 'posChain'
     */
    @Test
    public void posChainTest() {
        // TODO: test posChain
    }

    /**
     * Test the property 'unlockTimestamp'
     */
    @Test
    public void unlockTimestampTest() {
        // TODO: test unlockTimestamp
    }

    /**
     * Test the property 'unlockBlockHeight'
     */
    @Test
    public void unlockBlockHeightTest() {
        // TODO: test unlockBlockHeight
    }

    /**
     * Test the property 'stakeAddress'
     */
    @Test
    public void stakeAddressTest() {
        // TODO: test stakeAddress
    }

    /**
     * Test the property 'unbondAddress'
     */
    @Test
    public void unbondAddressTest() {
        // TODO: test unbondAddress
    }

    /**
     * Test the property 'beaconValidators'
     */
    @Test
    public void beaconValidatorsTest() {
        // TODO: test beaconValidators
    }

    /**
     * Test the property 'stakerAddress'
     */
    @Test
    public void stakerAddressTest() {
        // TODO: test stakerAddress
    }

    /**
     * Test the property 'validatorAddress'
     */
    @Test
    public void validatorAddressTest() {
        // TODO: test validatorAddress
    }

    /**
     * Test the property 'rewardAddress'
     */
    @Test
    public void rewardAddressTest() {
        // TODO: test rewardAddress
    }

    /**
     * Test the property 'timelock'
     */
    @Test
    public void timelockTest() {
        // TODO: test timelock
    }

}
