/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SwapTokenPair
 */
public class SwapTokenPairTest {
    private final SwapTokenPair model = new SwapTokenPair();

    /**
     * Model tests for SwapTokenPair
     */
    @Test
    public void testSwapTokenPair() {
        // TODO: test SwapTokenPair
    }

    /**
     * Test the property 'payTokenId'
     */
    @Test
    public void payTokenIdTest() {
        // TODO: test payTokenId
    }

    /**
     * Test the property 'receiveTokenId'
     */
    @Test
    public void receiveTokenIdTest() {
        // TODO: test receiveTokenId
    }

}
