/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.TransactionEvmContractMethod;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionEvmCalldataInfo
 */
public class TransactionEvmCalldataInfoTest {
    private final TransactionEvmCalldataInfo model = new TransactionEvmCalldataInfo();

    /**
     * Model tests for TransactionEvmCalldataInfo
     */
    @Test
    public void testTransactionEvmCalldataInfo() {
        // TODO: test TransactionEvmCalldataInfo
    }

    /**
     * Test the property 'chainId'
     */
    @Test
    public void chainIdTest() {
        // TODO: test chainId
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'implAddress'
     */
    @Test
    public void implAddressTest() {
        // TODO: test implAddress
    }

    /**
     * Test the property 'implName'
     */
    @Test
    public void implNameTest() {
        // TODO: test implName
    }

    /**
     * Test the property 'proxy'
     */
    @Test
    public void proxyTest() {
        // TODO: test proxy
    }

    /**
     * Test the property 'method'
     */
    @Test
    public void methodTest() {
        // TODO: test method
    }

    /**
     * Test the property 'params'
     */
    @Test
    public void paramsTest() {
        // TODO: test params
    }

}
