/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionSolContractAccount
 */
public class TransactionSolContractAccountTest {
    private final TransactionSolContractAccount model = new TransactionSolContractAccount();

    /**
     * Model tests for TransactionSolContractAccount
     */
    @Test
    public void testTransactionSolContractAccount() {
        // TODO: test TransactionSolContractAccount
    }

    /**
     * Test the property 'pubkey'
     */
    @Test
    public void pubkeyTest() {
        // TODO: test pubkey
    }

    /**
     * Test the property 'isSigner'
     */
    @Test
    public void isSignerTest() {
        // TODO: test isSigner
    }

    /**
     * Test the property 'isWritable'
     */
    @Test
    public void isWritableTest() {
        // TODO: test isWritable
    }

}
