/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.TravelRuleDepositRequestTravelRuleInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TravelRuleDepositRequest
 */
public class TravelRuleDepositRequestTest {
    private final TravelRuleDepositRequest model = new TravelRuleDepositRequest();

    /**
     * Model tests for TravelRuleDepositRequest
     */
    @Test
    public void testTravelRuleDepositRequest() {
        // TODO: test TravelRuleDepositRequest
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'travelRuleInfo'
     */
    @Test
    public void travelRuleInfoTest() {
        // TODO: test travelRuleInfo
    }

}
