/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.DestinationWalletType;
import com.cobo.waas2.model.SelfCustodyWallet;
import com.cobo.waas2.model.TravelRuleWithdrawExchangesOrVASP;
import com.cobo.waas2.model.TravelRuleWithdrawExchangesOrVASPEntityInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TravelRuleWithdrawRequestTravelRuleInfo
 */
public class TravelRuleWithdrawRequestTravelRuleInfoTest {
    private final TravelRuleWithdrawRequestTravelRuleInfo model = new TravelRuleWithdrawRequestTravelRuleInfo();

    /**
     * Model tests for TravelRuleWithdrawRequestTravelRuleInfo
     */
    @Test
    public void testTravelRuleWithdrawRequestTravelRuleInfo() {
        // TODO: test TravelRuleWithdrawRequestTravelRuleInfo
    }

    /**
     * Test the property 'destinationWalletType'
     */
    @Test
    public void destinationWalletTypeTest() {
        // TODO: test destinationWalletType
    }

    /**
     * Test the property 'selfCustodyWalletChallenge'
     */
    @Test
    public void selfCustodyWalletChallengeTest() {
        // TODO: test selfCustodyWalletChallenge
    }

    /**
     * Test the property 'selfCustodyWalletAddress'
     */
    @Test
    public void selfCustodyWalletAddressTest() {
        // TODO: test selfCustodyWalletAddress
    }

    /**
     * Test the property 'selfCustodyWalletSign'
     */
    @Test
    public void selfCustodyWalletSignTest() {
        // TODO: test selfCustodyWalletSign
    }

    /**
     * Test the property 'vendorCode'
     */
    @Test
    public void vendorCodeTest() {
        // TODO: test vendorCode
    }

    /**
     * Test the property 'vendorVaspId'
     */
    @Test
    public void vendorVaspIdTest() {
        // TODO: test vendorVaspId
    }

    /**
     * Test the property 'entityInfo'
     */
    @Test
    public void entityInfoTest() {
        // TODO: test entityInfo
    }

}
