/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.DestinationWalletType;
import com.cobo.waas2.model.TravelRuleWithdrawExchangesOrVASPEntityInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TravelRuleWithdrawExchangesOrVASP
 */
public class TravelRuleWithdrawExchangesOrVASPTest {
    private final TravelRuleWithdrawExchangesOrVASP model = new TravelRuleWithdrawExchangesOrVASP();

    /**
     * Model tests for TravelRuleWithdrawExchangesOrVASP
     */
    @Test
    public void testTravelRuleWithdrawExchangesOrVASP() {
        // TODO: test TravelRuleWithdrawExchangesOrVASP
    }

    /**
     * Test the property 'destinationWalletType'
     */
    @Test
    public void destinationWalletTypeTest() {
        // TODO: test destinationWalletType
    }

    /**
     * Test the property 'vendorCode'
     */
    @Test
    public void vendorCodeTest() {
        // TODO: test vendorCode
    }

    /**
     * Test the property 'vendorVaspId'
     */
    @Test
    public void vendorVaspIdTest() {
        // TODO: test vendorVaspId
    }

    /**
     * Test the property 'entityInfo'
     */
    @Test
    public void entityInfoTest() {
        // TODO: test entityInfo
    }

}
