/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TravelRuleDepositLegalEntity
 */
public class TravelRuleDepositLegalEntityTest {
    private final TravelRuleDepositLegalEntity model = new TravelRuleDepositLegalEntity();

    /**
     * Model tests for TravelRuleDepositLegalEntity
     */
    @Test
    public void testTravelRuleDepositLegalEntity() {
        // TODO: test TravelRuleDepositLegalEntity
    }

    /**
     * Test the property 'selectedEntityType'
     */
    @Test
    public void selectedEntityTypeTest() {
        // TODO: test selectedEntityType
    }

    /**
     * Test the property 'legalName'
     */
    @Test
    public void legalNameTest() {
        // TODO: test legalName
    }

    /**
     * Test the property 'dateOfIncorporation'
     */
    @Test
    public void dateOfIncorporationTest() {
        // TODO: test dateOfIncorporation
    }

    /**
     * Test the property 'placeOfIncorporation'
     */
    @Test
    public void placeOfIncorporationTest() {
        // TODO: test placeOfIncorporation
    }

}
